# Cpplint-only workflow (no need for compiler(s) to be installed)
name: cpplint

on:
  push:
    branches: [ master ]
    paths:
      # The workflow
      - ".github/workflows/cpplint.yml"
      # Any headers in any directory
      - "**.h"
      - "**.hpp"
      - "**.hxx"
      - "**.cuh"
      # Any source file in any directory
      - "**.c"
      - "**.cpp"
      - "**.cxx"
      - "**.cuh"
      # Any cmakelists in any directory
      - "**CMakeLists.txt"
      # Anything in a directory called `cmake`
      - "**cmake/**"
  pull_request: 
    branches: [ master ]
    paths:
      # The workflow
      - ".github/workflows/cpplint.yml"
      # Any headers in any directory
      - "**.h"
      - "**.hpp"
      - "**.hxx"
      - "**.cuh"
      # Any source file in any directory
      - "**.c"
      - "**.cpp"
      - "**.cxx"
      - "**.cuh"
      # Any cmakelists in any directory
      - "**CMakeLists.txt"
      # Anything in a directory called `cmake`
      - "**cmake/**"
jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install cpplint
      run: pip3 install cpplint && echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure
      run: cmake . -B build -DUSE_CPPLINT=ON -DUSE_CXX=OFF -DBUILD_TESTS=ON
      shell: bash

    - name: cpplint
      id: lint
      working-directory: build
      run: |
        set -o pipefail
        cmake --build . --target all_cpplint |& tee cpplint.log

    # - name: generate annotations
    #   if: ${{ failure() && steps.lint.outcome == 'failure' }}
    #   working-directory: build
    #   run: python3 ../scripts/actions-cpplint-annotations.py

       

