# Testing with build matrices 
name: MatrixTesting

# Pushes only, no need for pr 
on:
  push:

jobs:

  # Experiment with build matrices, to mirror combinations of OS, CUDA version and extra image specific variables
  # I.e. newer ubuntu only works with newer CUDAs. 
  # Can i specify multiple CUDAs for an OS in an include?


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        include:
          # Add an extra variable if the os is 1804?
          - os: ubuntu-18.04
            gcc: 10
          # Add an extra cuda version for 16.04
          - os: ubuntu-16.04
            cuda: 8.0
          # Add multiple cuda version at once?
          - os: ubuntu-16.04
            cuda: 11.0

    steps:
      - uses: actions/checkout@v2

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"