# Run on PR comments, has to be in master for issue_comment to trigger.
name: pr_comment


# Trigger this workflow when a pr is commented on with a valid keyword, from a legit user, otherwise, don't. 
# @todo - figure out how to register this as a status with the pr / reply to the pr with the status.
on:
  issue_comment:
    types: [created, edited]

# Run a job on PR open or issue comment.
jobs:
  run_on_pr_comment:
    # Run on issue comments, to issues which are actually a pull request, from legit authors, who mention the magical trigger.
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association) && startsWith(github.event.comment.body, '!actions CI')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    # Get the sha of the head from the api for this pull request.
    - name: get_pr_sha
      id: get_pr_sha
      run: |
        pr_head_sha=$(curl --request GET \
        --url ${{ github.event.issue.pull_request.url }} \
        | jq --raw-output -e '.head.sha')
        echo "::set-output name=pr_head_sha::$pr_head_sha"

    # @todo - switch to checks api once out of beta-this has the skipped option.
    - name: Register Pending
      id: register_pending
      run: |
        curl --request POST \
        --url ${{ github.event.repository.url }}/statuses/${{ steps.get_pr_sha.outputs.pr_head_sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "pending",
          "target_url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
          "description": "Pending",
          "context": "${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})"
        }' | jq --raw-output -e '.id' && \
        bot_comment_id=$(curl --request POST \
        --url ${{ github.event.issue.comments_url }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "body": "**Pending** GitHub Action :rocket: \n[${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})"
        }' | jq --raw-output -e '.id') && echo "::set-output name=bot_comment_id::$bot_comment_id" && \
        curl --request POST \
        --url ${{ github.event.comment.url }}/reactions \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'Accept: application/vnd.github.squirrel-girl-preview' \
        --header 'content-type: application/json' \
        --data '{
          "content": "rocket"
        }'


    - name: run-on-pr-comment
      run: | 
        echo "Successfully triggered by ${{ github.event.comment.user.login }} ( ${{ github.event.comment.author_association }})"
        echo "  commenting on PR ${{ github.event.issue.number }}"
        echo "  which contains trigger phrase '!FullCI'"
        echo "  comment:"
        echo "${{ github.event.comment.body }}" 
  
    # @todo - switch to checks api once out of beta-this has the skipped option.
    # @todo - make the comment reference the relevant issue to track which is which (in case of out of order?) 
    - name: Report Success
      if: success()
      run: |
        curl --request POST \
        --url ${{ github.event.repository.url }}/statuses/${{ steps.get_pr_sha.outputs.pr_head_sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "target_url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
          "description": "Success",
          "context": "${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})"
        }' | jq --raw-output -e '.id' && \
        curl --request PATCH \
        --url ${{ github.event.repository.url }}/issues/comments/${{ steps.register_pending.outputs.bot_comment_id }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "body": "**Successful** GitHub Action :+1: \n[${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})"
        }' | jq --raw-output -e '.id'
        
    # @todo - switch to checks api once out of beta-this has the skipped option.
    - name: Report Failure
      if: failure()
      run: |
        curl --request POST \
        --url ${{ github.event.repository.url }}/statuses/${{ steps.get_pr_sha.outputs.pr_head_sha }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "failure",
          "target_url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
          "description": "failure",
          "context": "${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})"
        }' | jq --raw-output -e '.id' && \
        curl --request PATCH \
        --url ${{ github.event.repository.url }}/issues/comments/${{ steps.register_pending.outputs.bot_comment_id }} \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "body": "**Failed** GitHub Action :-1: \n[${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }})"
        }' | jq --raw-output -e '.id'