# Run on PR comments, has to be in master for issue_comment to trigger.
name: pr_comment


# Trigger this workflow when a pr is commented on with a valid keyword, from a legit user, otherwise, don't. 
# @todo - figure out how to register this as a status with the pr / reply to the pr with the status.
on:
  issue_comment:
    types: [created, edited]

# Run a job on PR open or issue comment.
jobs:
  run_on_pr_comment:
    # Run on issue comments, to issues which are actually a pull request, from legit authors, who mention the magical trigger.
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && contains('OWNER,MEMBER,COLLABORATOR', github.event.comment.author_association) && contains(github.event.comment.body, '!FullCI')
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: run-on-pr-comment
      run: | 
        echo "Successfully triggered by ${{ github.event.comment.user.login }} ( ${{ github.event.comment.author_association }})"
        echo "  commenting on PR ${{ github.event.issue.number }}"
        echo "  which contains trigger phrase '!FullCI'"
        echo "  comment:"
        echo "${{ github.event.comment.body }}" 
    
    - name: Report status
        run: |
          curl --request POST \
          --url ${{ github.repository.statuses_url }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "target_url": "${{ github.repository_url }}/actions/runs/${{ github.run_id }}",
            "description": "Successful in Xs",
            "context": "${{ github.workflow }} / ${{ github.job }} (${{ github.event_name }})"
            }'
        if: success()