# Github action triggered by label, or by pr with label.

name: pr_or_labelled

# Build if a direct push to master, or a PR is approved.
on:
  # push:
    # branches: [ master ]
    # temp run on any push which changes the file.
    # paths: 
    #   - ".github/workflows/thorough.yml"
  # Trigger on pull requests, when opened, synced or reoponed (job 1), or labeled (job2).
  # Jobs should only run if labelled with FullCI ()
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  
  pull_request_review:
    types: [submitted, edited, dismissed]

# @todo - edge case - PRs from external repos, where lablled/approved by team, but then 
jobs:
  run_on_pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: run-on-pr
      run: echo "run-on-pr"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: pr_new_label
      if: github.event.action == 'labeled'
      run: echo " New label ${{ github.event.label.name }}"

    - name: pr_if_has_label_FullCI
      if: contains(github.event.pull_request.labels.*.name, 'FullCI')
      run: echo "PR ${{ github.event.pull_request.number }} Has FullCI label"
    
    # @todo pr_if_approved

    - name: pr_is_open
      if: github.event.pull_request.state == 'open'
      run: echo "PR ${{ github.event.pull_request.number }} is open"


  run_on_review:
    if: github.event_name == 'pull_request_review'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: run-on-prr
      run: echo "run-on-prr"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    # "state": "APPROVED"
    # - name: pr_if_has_label_FullCI
    #   if: contains(github.event.pull_request.labels.*.name, 'FullCI')
    #   run: echo "PR ${{ github.event.pull_request.number }} Has FullCI label"