# Workflow for releases
name: releases

# Handle release events - this workflow needs to be present in the tag beign applied?


# github release UI options
# - Creting a new release from an existing tag:
#    - Triggers published + (pre)released + (maybe/sometimes) created
# - creating a new release without a tag
#    - Triggers published + push.tag + (pre)released.
#    - Did not get a creaed event, as it was originally created as a draft.



# Release types / actions:
  # - published - when a draft release is published.
  # - unpublished - Not sure how to trigger this from the github UI
  # - created - This appears to be triggered sometimes from the ui but not always - release, created and published from same commit at the same time?
  # - edited - When release body/name is edited? 
  # - deleted - delete button.
  # - prereleased - when publshed && is marked as a pre-release
  # - released - when published && is not marked as a pre-release

# Force pushing a tag to a different commit does not re-trigger the release! - should have a on.push.tag which checks if tehre is an assocated release and if so does any extra objects?

on:
  release:
    types: 
      - published
      - unpublished
      - created
      - edited
      - deleted
      - prereleased
      - released


jobs:
  do_release:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Configure
        run: cmake . -B build
        shell: bash

      # - name: build
      #   run: cmake --build . --target all 
      #   working-directory: build
