# Workflow for tags and releases
name: tag

# Tagged commits by an approved author should trigger thorough builds - 
# Possibly only tags which represent a version number?
# This could then potentially be checked on release creation.


# force pushes to tags do not - re-trigger any release event, but they do re-trigger the push.tag
# If the release is created from an un-tagged commit, there is no guarantee that this (the push.tag action) has completed or been issued prior to the release action. Probably best to activate on both (although then may double-trigger?)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 

jobs:
  do_tag:
    runs-on: ubuntu-18.04
    env:
      create_release: true

    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Configure
        run: cmake . -B build
        shell: bash

      - name: build
        run: cmake --build . --target all 
        working-directory: build

      - name: create artifact
        run: zip -r build.zip build

      # create a release 
      - name: create release
        if: success() && env.create_release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Release ${{ github.ref }}\n: Changelog @todo"
          draft: false
          prerelease: false

      # Upload the artifact to the created release
      - name: upload
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: build.zip
          asset_content_type: application/zip


  

