# Thorough workflow triggered when a PR is approved.
# @todo - check team membership via web api?  https://developer.github.com/v3/teams/members/
# github.event.pusher.name ?
name: thorough

# Build if a direct push to master, or a PR is approved.
on:
  push:
    # branches: [ master ]
    # temp run on any push which changes the file.
    # paths: 
    #   - ".github/workflows/thorough.yml"
  pull_request_review:
    types: [submitted, edited, dismissed]



jobs:
  trigger-check:
    runs-on:  ubuntu-18.04


    steps:
    - uses: actions/checkout@v2

    - name: Trigger_check
      run: |
        echo "This has been triggered?"
        echo "github.actor = ${{ github.actor }}"	
   
    - name: Echo state
      run: |
        echo "github.event"
        echo "${{ github.event.action }}"
        echo "${{ github.event.pull_request }}"
        echo "${{ github.event.review }}"
        echo "${{ github.event.changes }}"
        echo "${{ github.event.organization }}"
        echo "${{ github.event.installation }}"
        echo "${{ github.event.sender }}"
        echo "--"
        echo "${{ github.actor }}"
        echo "${{ github.repository_owner }}"