# Ubuntu 18.04
name: Ubuntu1604

# Only build if relevant files changes?
on:
  push:
    branches: [ master ]
    paths:
      # Add everything
      - "**"
      # Exclude some things
      - "!docs/**"
      - "!.gitignore"
      - "!**.md"
      - "!.github/**"
      - "!scripts/**"
      # Re-include special cases
      - ".github/workflows/Ubuntu1804.yml"
  # Trigger on all PRs?
  pull_request:
    paths:
      # Add everything
      - "**"
      # Exclude some things
      - "!docs/**"
      - "!.gitignore"
      - "!**.md"
      - "!.github/**"
      - "!scripts/**"
      # Re-include special cases
      - ".github/workflows/Ubuntu1804.yml"


jobs:
  build:
    runs-on:  ubuntu-18.04
    # env:

    steps:
    - uses: actions/checkout@v2

    # - name: Install cpplint
    #   run: pip3 install cpplint && echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure
      id: configure
      run: |
        mkdir -p build
        cd build
        cmake .. \ 
          -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Configure Error Processing
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi
      shell: bash
      working-directory: build
      if: ${{ failure() && steps.configure.outcome == 'failure' }}

    - name: Build
      id: build
      working-directory: build
      run: |
        set -o pipefail
        cmake --build . --target all --verbose -j 2 |& tee CMakeBuild.log

    - name: generate annotations
      if: ${{ failure() && steps.build.outcome == 'failure' }}
      working-directory: build
      run: python3 ../scripts/actions-gcc-annotations.py
    
    - name: Test
      run: ctest  -VV -j2
      shell: bash
      working-directory: build