# Ubuntu 18.04
name: Ubuntu1804

# Only build if relevant files changes?
on:
  push:
    branches: [ master ]
    paths:
      # Add everything
      - "**"
      # Exclude some things
      - "!docs/**"
      - "!.gitignore"
      - "!**.md"
      - "!.github/**"
      - "!scripts/**"
      # Re-include special cases
      - ".github/workflows/Ubuntu1804.yml"
      - ".github/problem-matchers/"

  # Trigger on all PRs?
  pull_request:
    paths:
      # Add everything
      - "**"
      # Exclude some things
      - "!docs/**"
      - "!.gitignore"
      - "!**.md"
      - "!.github/**"
      - "!scripts/**"
      # Re-include special cases
      - ".github/workflows/Ubuntu1804.yml"
      - ".github/problem-matchers/"


jobs:
  build:
    runs-on:  ubuntu-18.04
    strategy:
      fail-fast: false
    # env:

    steps:
    - uses: actions/checkout@v2

    # Apply the matcher, this might not work without the matcher living on its own.
    # - name: apply matcher
    #   run: echo "::add-matcher::.github/problem-matchers/matcher.json"
    
    
    - name: apply json matcher
      run: echo "::add-matcher::jsonval-matcher.json"

    - name: dumb test
      run: |
        echo "WARN: myconfig.json:1:4: Unexpected token '}'"

    - name: dumb test
      run: |
        echo "ERROR: myconfig.json:1:4: Unexpected token '}'"


    # - name: Install cpplint
    #   run: pip3 install cpplint && echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure
      id: configure
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Configure Error Processing
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi
      shell: bash
      working-directory: build
      if: ${{ failure() && steps.configure.outcome == 'failure' }}

    - name: Build
      id: build
      working-directory: build
      run: |
        set -o pipefail
        cmake --build . --target all --verbose -j 2 |& tee CMakeBuild.log

    # - name: generate annotations
    #   if: ${{ failure() && steps.build.outcome == 'failure' }}
    #   working-directory: build
    #   run: python3 ../scripts/actions-gcc-annotations.py
    
    - name: Test
      run: ctest  -VV -j2
      shell: bash
      working-directory: build