name: Ubuntu-apt-downgrade

# Only build if relevant files changes?
on:
  push:
    branches: [ "**" ]
    paths:
      - ".github/workflows/ubuntu-apt-downgrade.yml"
  workflow_dispatch:


jobs:
  build:
    runs-on:  ${{ matrix.os }}
    container:
      image: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-20.04"
          # - "ubuntu-22.04"
        container:
          - "ubuntu:jammy"
          - null

    steps:
    - uses: actions/checkout@v2

    - name: List OS
      run: |
        cat /etc/os-release

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Show installed libexpat versions
      run: |
        dpkg -l | grep libexpat1 || true

    - name: Downgrade libexpat
      if: ${{ (runner.os == 'Linux' && matrix.os == 'ubuntu-22.04') || job.container != null }}
      run: |
        if dpkg -l | grep libexpat1-dev | grep 2.4.7-1ubuntu0.3; then
          sudo apt-get install -y --allow-downgrades libexpat1=2.4.7-1 libexpat1-dev=2.4.7-1
          sudo apt-mark hold libexpat1 libexpat1-dev
        fi

    - name: Show installed libexpat versions
      run: |
        dpkg -l | grep libexpat1

    - name: Error if bad libexpat1-dev
      run: dpkg -l | grep libexpat1-dev | grep -v 2.4.7-1ubuntu0.3 